version: '3.7'
services:
  service-registry:
    build: ./service-registry
    #image: barathece91/spring-cloud-gateway-eureka-server
    ports:
      - "8761:8761"
    networks:
      - springboot-db-net
  cloud-gateway:
    build: ./cloud-gateway
    ports:
      - "8081:8081"
    depends_on:
      - service-registry
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    networks:
      - springboot-db-net
  employee-service:
    build: ./employee-service
    ports:
      - "8082:8082"
    depends_on:
      - service-registry
      - mysql-db
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/employee_db?allowPublicKeyRetrieval=true
    networks:
      - springboot-db-net
    volumes:
      - /data/springboot-app
  project-service:
    build: ./project-service
    ports:
      - "8083:8083"
    depends_on:
      - service-registry
      - mysql-db
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/employee_db?allowPublicKeyRetrieval=true
    networks:
      - springboot-db-net
    volumes:
      - /data/springboot-app
  training-service:
    build: ./training-service
    ports:
      - "8084:8084"
    depends_on:
      - service-registry
      - mysql-db
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/employee_db?allowPublicKeyRetrieval=true
    networks:
      - springboot-db-net
    volumes:
      - /data/springboot-app
  mysql-db:
    image: mysql:8
    networks:
      - springboot-db-net
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=employee_db
      - MYSQL_USER=prashant
      - MYSQL_PASSWORD=root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  springboot-db-net: